apiVersion: v1
kind: Service
metadata:
  name: sales-api
  namespace: sales-system

spec:
  selector:
    app: sales

  type: ClusterIP

  ports:
    # expose the ports within the cluster
    - name: sales-api
      port: 3000
      targetPort: sales-api # this name is defined in k8s/base/base-sales.yaml in the deployment's containers section

    - name: sales-api-debug
      port: 4000
      targetPort: sales-api-debug # this name is defined in k8s/base/base-sales.yaml in the deployment's containers section