apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/sales/
patches:
  - path: ./dev-sales-patch-deploy.yaml
  - path: ./dev-sales-patch-service.yaml
images:
  # replace service-image that we have defined in base/sales/base-sales.yaml , with the newName and newTag that we have defined.
  - name: service-image
    newName: ardanlabs/service/sales-api
    newTag: 0.0.5
